name: Set recent blog post in README

on:
    schedule:
        - cron: "*/30 * * * *"
    push:
        paths:
            - "scripts/blog-post.sh"
    workflow_dispatch:

jobs:
    update-readme-blog-post:
        name: Update README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run script
              run: bash ./scripts/blog-post.sh || bash ./scripts/send-notification.sh -m "🚨 Failed to update blog post"
              env:
                  DISCORD_WEBHOOK_URI: ${{ secrets.DISCORD_WEBHOOK_URI }}
            - name: Commit
              run: bash ./scripts/commit.sh -m "Update blog post" || bash ./scripts/send-notification.sh -m "Failed to commit changes"
              env:
                  DISCORD_WEBHOOK_URI: ${{ secrets.DISCORD_WEBHOOK_URI }}
