name: Random image workflow
on:
    schedule:
        - cron: "0 6 * * *"
    workflow_dispatch:
jobs:
    update-readme-image:
        name: Update greeting image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: node ./scripts/random-image.js
            # Code from https://stackoverflow.com/a/58393457
            - name: load to github
              run: |
                  git config --global user.name 'image-updater'
                  git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
                  git commit -am "Update image"
                  git push
