name: Latest blog post workflow
on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:
jobs:
    update-readme-image:
        name: Update greeting image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: node ./scripts/random-image.js
