name: Set random image in README with Shell Script

on:
    # schedule:
    #     - cron: "0 15 * * *"
    # push:
    #     paths:
    #         - "scripts/random-image.sh"
    workflow_dispatch:

jobs:
    update-readme-image:
        name: Update greeting image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run script
              run: bash scripts/random-image.sh
              env:
                  IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
            - name: Commit
              run: bash scripts/commit.sh -m "Update image"
